slurm:
  nnodes: 1
  walltime: 00:30:00
  qos: debug
  account: m3792 #m4637 #m3792 - nersc
  constraint: cpu

jrm:
  nodename: vk-nersc-fw
  site: nersc
  control_plane_ip: jiriaf2301
  apiserver_port: 35679
  kubeconfig: /global/homes/j/jlabtsai/config/kubeconfig
  vkubelet_pod_ip: "172.17.0.1"
  kubelet_port: 10000
  image: docker:jlabtsai/vk-cmd:main

ssh:
  apiserver: login04
  metrics_server: login04
